name: 'Code Signing Action'
description: 'Digitally signs executables and verifies the signature using signtool'
author: 'Encryption Consulting LLC'

inputs:
  file-path:
    description: 'Path to the file that needs to be signed'
    required: true
  cert-path:
    description: 'Path to the signing certificate (.crt file)'
    required: true
  key-container:
    description: 'Key container name'
    required: true
    default: 'ovcodesigning'
  timestamp-server:
    description: 'Timestamp server URL'
    required: false
    default: 'http://timestamp.sectigo.com'

runs:
  using: "composite"
  steps:
    - name: Sign Executable
      shell: pwsh
      run: |
        Write-Host "Signing the file: ${{ inputs.file-path }}"
        signtool sign /csp "Encryption Consulting Key Storage Provider" /kc "${{ inputs.key-container }}" /fd SHA256 /f "${{ inputs.cert-path }}" /tr "${{ inputs.timestamp-server }}" /td SHA256 "${{ inputs.file-path }}"

    - name: Verify Signature
      shell: pwsh
      run: |
        Write-Host "Verifying the signed file..."
        signtool verify /pa "${{ inputs.file-path }}"
