name: 'Code Signing Action'
description: 'Digitally signs executables and verifies the signature using signtool'
author: 'Encryption Consulting LLC'

inputs:
  file-path:
    description: 'Path to the file that needs to be signed'
    required: true
  cert-path:
    description: 'Path to the signing certificate (.crt file)'
    required: true
  key-container:
    description: 'Key container name'
    required: true
    default: 'ovcodesigning'
  timestamp-server:
    description: 'Timestamp server URL'
    required: false
    default: 'http://timestamp.sectigo.com'

- name: Run signtool using full path
  shell: pwsh
  run: |
    & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\signtool.exe" sign `
      /csp "Encryption Consulting Key Storage Provider" `
      /kc BechtelTest2 `
      /fd SHA256 `
      /f "C:\Users\sam\Desktop\CodeSign Secure\Signing Certificates\BechtelTest2.crt" `
      /tr http://timestamp.digicert.com `
      /td SHA256 `
      "C:\Users\sam\Desktop\CodeSign Secure\Sample Signing Files\winsdksetup.exe"
