name: Code Signing and Verification Workflow

on:
  push:
    branches:
      - main

jobs:
  sign-and-verify:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Code Signing Action
        uses: Encryption-Consulting-LLC/CodeSigning-Action@v1
        with:
          file-path: 'C:\Users\sam\Desktop\CodeSign Secure\Sample Signing Files\winsdksetup.exe'
          cert-path: 'C:\Users\sam\Desktop\CodeSign Secure\Signing Certificates\BechtelTest2.crt'
          key-container: 'BechtelTest2'
          timestamp-server: 'http://timestamp.sectigo.com'
          
