name: Using full path

on:
  workflow_dispatch:

jobs:
  sign-and-verify:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Code Signing Action
        uses: ./ 
        with:
          file-path: 'C:\Users\sam\Desktop\CodeSign Secure\Sample Signing Files\winsdksetup.exe'
          cert-path: 'C:\Users\sam\Desktop\CodeSign Secure\Signing Certificates\BechtelTest2.crt'
          key-container: 'BechtelTest2'
          timestamp-server: 'http://timestamp.sectigo.com'
