name: Using full path

on:
  push:
    branches:
      - main

jobs:
  sign:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check runner user
        run: whoami
        shell: cmd

      - name: Run Code Signing Action
        uses: ./ 
        with:
          file-path: C:\CodeSigningFiles\winsdksetup.exe
          cert-path: C:\CodeSigningFiles\BechtelTest2.crt
          key-container: 'BechtelTest2'
          timestamp-server: 'http://timestamp.sectigo.com'
