name: Using full path

on:
  push:
    branches:
      - main

jobs:
  sign-and-verify:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Code Signing Action
        uses: ./ 
        with:
          file-path: 'C:\Users\sam\Desktop\winsdksetup.exe'
          cert-path: 'C:\Users\sam\Desktop\BechtelTest2.crt'
          key-container: 'BechtelTest2'
          timestamp-server: 'http://timestamp.sectigo.com'
